import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    name: 'home',
    component:()=>import('@/views/home/home'),
    redirect: "/insuranceShop",
    children:[
      {
        path:'/insuranceShop',
        component:()=>import('@/views/insuranceShop/insuranceShop'),
        meta:{
          title:"中银三星人寿"
        }
      },
      {
        path:'/my',
        component:()=>import('@/views/my/my'),
        meta:{
          title:"中银三星人寿"
        }
      }
    ],
  },
  {
    path:'/previewList',
    component:()=>import('@/views/my/previewList/previewList'),
    meta:{
      title:"保单预览列表"
    }
  },
  {
    path:'/policydetails',
    component:()=>import('@/views/my/policyDetails/policydetails'),
    meta:{
      title:"保单详情"
    }
  },
  {
    path:'/acknowledgementreceipt',
    component:()=>import('@/views/my/acknowledgementReceipt/acknowledgementreceipt'),
    meta:{
      title:"回执签收"
    }
  },
  {
    path:'/userInfoEdit',
    component:()=>import('@/views/my/userInfoEdit/userinfoedit'),
    meta:{
      title:"客户资料变更"
    }
  },
  {
    path:'/userContactEdit',
    component:()=>import('@/views/my/userInfoEdit/usercontactedit'),
    meta:{
      title:"联系方式变更"
    }
  },
  {
    path:'/checkMobile',
    component:()=>import('@/views/my/userInfoEdit/checkmobile'),
    meta:{
      title:"手机验证"
    }
  },
  {
    path:'/getuniversalinsurance',
    component:()=>import('@/views/my/getUniversalInsurance/getuniversalinsurance'),
    meta:{
      title:"万能险部分领取"
    }
  },
  {
    path:'/terminatecontract',
    component:()=>import('@/views/my/terminateContract/terminatecontract'),
    meta:{
      title:"合同解除"
    }
  },
  {
    path:'/supplementarycalls',
    component:()=>import('@/views/my/supplementaryCalls/supplementarycalls'),
    meta:{
      title:"万能险追加保费"
    }
  },
  {
    path:'/beneficiary',
    component:()=>import('@/views/my/beneficiary/beneficiary'),
    meta:{
      title:"变更/新增受益人资料"
    }
  },
  {
    path:'/addbeneficiary',
    component:()=>import('@/views/my/beneficiary/addbeneficiary'),
    meta:{
      title:"新增受益人资料"
    }
  },
  {
    path:'/changemode',
    component:()=>import('@/views/my/changeMode/changemode'),
    meta:{
      title:"保费逾期未付处理方式变更"
    }
  },
  {
    path:'/stoprenewal',
    component:()=>import('@/views/my/stopRenewal/stoprenewal'),
    meta:{
      title:"短期险终止续保"
    }
  },
  {
    path:'/getbonus',
    component:()=>import('@/views/my/getBonus/getbonus'),
    meta:{
      title:"红利领取"
    }
  },
  {
    path:'/editbonus',
    component:()=>import('@/views/my/getBonus/editbonus'),
    meta:{
      title:"红利实现方式变更"
    }
  },
  {
    path:'/changefrequency',
    component:()=>import('@/views/my/changeFrequency/changefrequency'),
    meta:{
      title:"交费频率变更"
    }
  },
  {
    path:'/shortstoprenewal',
    component:()=>import('@/views/my/shortStopRenewal/shortstoprenewal'),
    meta:{
      title:"短期险终止续保"
    }
  },
  {
    path:'/defer',
    component:()=>import('@/views/my/defer/defer'),
    meta:{
      title:"万能险保费缓交变更"
    }
  },
  {
    path:'/payinsurancecost',
    component:()=>import('@/views/my/payInsuranceCost/payinsurancecost'),
    meta:{
      title:"万能险补交续期保费"
    }
  },
  {
    path:'/changeregularpremium',
    component:()=>import('@/views/my/changeRegularPremium/changeregularpremium'),
    meta:{
      title:"万能险补交续期保费"
    }
  },
  {
    path:'/accountlinking',
    component:()=>import('@/views/my/accountLinking/accountlinking'),
    meta:{
      title:"续期保费账户关联"
    }
  },
  {
    path:'/changepaytypeandrenew',
    component:()=>import('@/views/my/changePayTypeAndRenew/changepaytypeandrenew'),
    meta:{
      title:"续期交费方式及交费账号变更"
    }
  },
  {
    path:'/automaticdischarge',
    component:()=>import('@/views/my/automaticDischarge/automaticdischarge'),
    meta:{
      title:"自动垫交清偿"
    }
  },
  {
    path:'/changerenewaltype',
    component:()=>import('@/views/my/changeRenewalType/changerenewaltype'),
    meta:{
      title:"续期信函方式变更"
    }
  }
]

const router = new VueRouter({
  routes,
  scrollBehavior (to, from, savedPosition) {
    return { x: 0, y: 0 }
  }
})
export default router
